---
- name: "Install Docker using official repositories (Debian Bookworm)"
  block:
    - name: "Install required packages"
      apt:
        name: "ca-certificates curl gnupg lsb-release"
        state: present
        update_cache: true
    - name: "Add Docker GPG key"
      apt_key:
        url: "https://download.docker.com/linux/debian/gpg"
        state: present
    - name: "Add Docker apt repository for Debian Bookworm"
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: "docker"

    - name: "Install Docker packages"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: "Start and enable Docker service"
      service:
        name: docker
        state: started
        enabled: true

    - name: "Add user to the docker group"
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes
      become: true
