---
- name: "Installing Golang"
  apt:
    name: "golang-go"
    state: present
  become: true
  become_method: sudo

- name: "Installing Python Azure"
  apt:
    name: "python3-azure"
    state: present
  become: true
  become_method: sudo

- name: "Installing VMWare Tools For fix shorcuts issues"
  apt:
    name: "open-vm-tools open-vm-tools-desktop"
    state: present
  become: true
  become_method: sudo
  
- name: "Installing Redis"
  apt:
    name: "redis"
    state: present
  become: true
  become_method: sudo

# Installing Firejail from source
- name: "Cloning Firejail repository"
  git:
    repo: "https://github.com/netblue30/firejail.git"
    dest: "/tmp/firejail"

- name: "Installing firejail"
  shell: |
    cd /tmp/firejail
    ./configure && make && make install-strip
  become: true
  become_method: sudo
